name: Solar Theme
url: http://example.org
description: A stylish blog using the Solarized color palette
baseurl: "/TFM"

permalink: /:year/:month/:day/:title/
paginate: 10
pygment: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
