name: Ruben's Master Thesis
url: http://example.org
baseurl: "/TFM"
description: A comparative study of computational intelligence software for enhancing the capabilities of business document management systems

permalink: /:year/:month/:day/:title/
paginate: 10
pygment: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
